code_lexicon = {'Swahili': 'sw', 'Swedish': 'sv', 'Icelandic': 'is', 
        'Estonian': 'et', 'Telugu': 'te', 'Turkish': 'tr', 'Romanian': 'ro', 
        'Italian': 'it', 'Azerbaijani': 'az', 'Slovenian': 'sl', 
        'Gujarati': 'gu', 'Hindi': 'hi', 'Spanish': 'es', 'Dutch': 'nl', 
        'Norwegian': 'no', 'Korean': 'ko', 'Russian': 'ru', 'Danish': 'da', 
        'Bulgarian': 'bg', 'Latin': 'la', 'Vietnamese': 'vi', 'Finnish': 'fi', 
        'Hungarian': 'hu', 'Macedonian': 'mk', 'Welsh': 'cy', 
        'Chinese Traditional': 'zh-TW', 'Georgian': 'ka', 'Lithuanian': 'lt', 
        'Malay': 'ms', 'French': 'fr', 'Chinese Simplified': 'zh-CN', 
        'Catalan': 'ca', 'Bengali': 'bn', 'Maltese': 'mt', 'Thai': 'th', 
        'Afrikaans': 'af', 'Tamil': 'ta', 'Filipino': 'tl', 'Albanian': 'sq', 
        'Hebrew': 'iw', 'Indonesian': 'id', 'Greek': 'el', 
        'Haitian Creole': 'ht', 'Latvian': 'lv', 'English': 'en', 
        'Serbian': 'sr', 'Esperanto': 'eo', 'Croatian': 'hr', 
        'Portuguese': 'pt', 'Irish': 'ga', 'Czech': 'cs', 'Ukrainian': 'uk', 
        'Japanese': 'ja', 'Belarusian': 'be', 'Kannada': 'kn', 
        'Galician': 'gl', 'German': 'de', 'Persian': 'fa', 'Slovak': 'sk', 
        'Yiddish': 'yi', 'Basque': 'eu', 'Urdu': 'ur', 'Polish': 'pl', 
        'Arabic': 'ar'}